// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAlNWHaKNfTCh_Ny6i31unVkdvDMsNMTs',
    appId: '1:346733065047:web:aaa4f1e3494c7dabba0412',
    messagingSenderId: '346733065047',
    projectId: 'fir-javier-9fd0a',
    authDomain: 'fir-javier-9fd0a.firebaseapp.com',
    databaseURL: 'https://fir-javier-9fd0a-default-rtdb.firebaseio.com',
    storageBucket: 'fir-javier-9fd0a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAlNWHaKNfTCh_Ny6i31unVkdvDMsNMTs',
    appId: '1:346733065047:android:f80a9353cd095819ba0412',
    messagingSenderId: '346733065047',
    projectId: 'fir-javier-9fd0a',
    databaseURL: 'https://fir-javier-9fd0a-default-rtdb.firebaseio.com',
    storageBucket: 'fir-javier-9fd0a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAlNWHaKNfTCh_Ny6i31unVkdvDMsNMTs',
    appId: '1:346733065047:ios:PENDING',
    messagingSenderId: '346733065047',
    projectId: 'fir-javier-9fd0a',
    databaseURL: 'https://fir-javier-9fd0a-default-rtdb.firebaseio.com',
    storageBucket: 'fir-javier-9fd0a.firebasestorage.app',
    iosBundleId: 'com.example.appIotSistemaRiego',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAlNWHaKNfTCh_Ny6i31unVkdvDMsNMTs',
    appId: '1:346733065047:macos:PENDING',
    messagingSenderId: '346733065047',
    projectId: 'fir-javier-9fd0a',
    databaseURL: 'https://fir-javier-9fd0a-default-rtdb.firebaseio.com',
    storageBucket: 'fir-javier-9fd0a.firebasestorage.app',
    iosBundleId: 'com.example.appIotSistemaRiego',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAlNWHaKNfTCh_Ny6i31unVkdvDMsNMTs',
    appId: '1:346733065047:windows:PENDING',
    messagingSenderId: '346733065047',
    projectId: 'fir-javier-9fd0a',
    authDomain: 'fir-javier-9fd0a.firebaseapp.com',
    databaseURL: 'https://fir-javier-9fd0a-default-rtdb.firebaseio.com',
    storageBucket: 'fir-javier-9fd0a.firebasestorage.app',
  );
}
